version: "2.2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.4.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://192.168.1.40:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'

  schema-registry:
    image: confluentinc/cp-schema-registry:5.4.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'

  elasticsearch:
    image: elasticsearch:7.16.2
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: 'Aa123456'
  kibana:
    image: kibana:7.16.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

  process_a:
    image: test:0.1.2
    environment:
      SHOULD_INITIALIZE_PRODUCER: 'true'
      NUMBER_OF_MESSAGES_TO_PRODUCE: '10'
      PRODUCE_TO_TOPIC: 'A'
      PROCESS_NAME: 'process_a'
      LOG_LEVEL: 'DEBUG'
      KAFKA_ADDRESS: '192.168.1.40:9092'
      SCHEMA_REGISTRY_URL: 'http://192.168.1.40:8081'
      SLEEP_BETWEEN_SENDS_MILLIS: '1000'
    depends_on:
      - kafka
      - zookeeper
      - schema-registry

  process_b:
    image: test:0.1.2
    environment:
      SHOULD_INITIALIZE_PRODUCER: 'true'
      SHOULD_INITIALIZE_CONSUMER: 'true'
      NUMBER_OF_MESSAGES_TO_PRODUCE: '10'
      CONSUME_FROM_TOPIC: 'A'
      PRODUCE_TO_TOPIC: 'B'
      PROCESS_NAME: 'process_b'
      LOG_LEVEL: 'DEBUG'
      KAFKA_ADDRESS: '192.168.1.40:9092'
      SCHEMA_REGISTRY_URL: 'http://192.168.1.40:8081'
      SLEEP_BETWEEN_SENDS_MILLIS: '15'
    depends_on:
      - kafka
      - zookeeper
      - schema-registry
  process_c:
    image: test:0.1.2
    environment:
      SHOULD_INITIALIZE_PRODUCER: 'true'
      SHOULD_INITIALIZE_CONSUMER: 'true'
      NUMBER_OF_MESSAGES_TO_PRODUCE: '10'
      CONSUME_FROM_TOPIC: 'B'
      PRODUCE_TO_TOPIC: 'C'
      PROCESS_NAME: 'process_c'
      LOG_LEVEL: 'DEBUG'
      KAFKA_ADDRESS: '192.168.1.40:9092'
      SCHEMA_REGISTRY_URL: 'http://192.168.1.40:8081'
      SLEEP_BETWEEN_SENDS_MILLIS: '15'
    depends_on:
      - kafka
      - zookeeper
      - schema-registry
  process_d:
    image: test:0.1.2
    environment:
      SHOULD_INITIALIZE_PRODUCER: 'true'
      SHOULD_INITIALIZE_CONSUMER: 'true'
      NUMBER_OF_MESSAGES_TO_PRODUCE: '10'
      CONSUME_FROM_TOPIC: 'C'
      PRODUCE_TO_TOPIC: 'D'
      LOG_LEVEL: 'DEBUG'
      PROCESS_NAME: 'process_d'
      KAFKA_ADDRESS: '192.168.1.40:9092'
      SCHEMA_REGISTRY_URL: 'http://192.168.1.40:8081'
      SLEEP_BETWEEN_SENDS_MILLIS: '15'
    depends_on:
      - kafka
      - zookeeper
      - schema-registry
  process_e:
    image: test:0.1.2
    environment:
      SHOULD_INITIALIZE_PRODUCER: 'true'
      SHOULD_INITIALIZE_CONSUMER: 'true'
      NUMBER_OF_MESSAGES_TO_PRODUCE: '10'
      CONSUME_FROM_TOPIC: 'D'
      PRODUCE_TO_TOPIC: 'E'
      PROCESS_NAME: 'process_e'
      LOG_LEVEL: 'DEBUG'
      KAFKA_ADDRESS: '192.168.1.40:9092'
      SCHEMA_REGISTRY_URL: 'http://192.168.1.40:8081'
      SLEEP_BETWEEN_SENDS_MILLIS: '15'
    depends_on:
      - kafka
      - zookeeper
      - schema-registry

  data_collector:
    image: data_collector:0.1.1
    environment:
      KAFKA_ADDRESS: '192.168.1.40:9092'
      SCHEMA_REGISTRY_URL: 'http://192.168.1.40:8081'
      LOG_LEVEL: 'DEBUG'
      ELASTIC_HOST: '192.168.1.40'
      ELASTIC_USER_NAME: 'elastic'
      ELASTIC_PASSWORD: 'Aa123456'
    depends_on:
      - kafka
      - zookeeper
      - elasticsearch
      - schema-registry
