/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.last.process;

import java.util.List;

public class Main {
    public static void main(String[] args) {
        String consumerTopic = "FROM-MIDDLE-TO-END";
        String destinationTopic = "END";
        MyKafkaProducer kafkaProducer = new MyKafkaProducer();
        DataProcessor p = new DataProcessor(kafkaProducer, destinationTopic);
        final MyKafkaConsumer consumer = new MyKafkaConsumer<>(p);
        consumer.subscribe(List.of(consumerTopic));
        consumer.startConsume();
    }
}
